onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp
ignoredBuiltDependencies:
  # unrs-resolver postinstall only required for npm <v11 bug
  # - https://github.com/unrs/unrs-resolver/issues/85#issuecomment-3435918759
  - unrs-resolver
# Prevents installation of packages newer than 7 days
# to mitigate supply chain risks
# - https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@upleveled/*'
  - eslint-config-upleveled
  - stylelint-config-upleveled
  # Renovate security update: next@16.1.5
  - next@16.1.5
  # Renovate security update: swiper@12.1.2
  - swiper@12.1.2
# Fail on pnpm ignored build scripts
# - https://pnpm.io/settings#strictdepbuilds
strictDepBuilds: true
